name: Update versi_python and Update OpenClash

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get latest release version of python-telegram-bot
        id: get_release
        run: |
          max_retries=5
          attempt=1
          latest_version=""
          while [ -z "$latest_version" ] && [ $attempt -le $max_retries ]; do
            echo "Attempt $attempt to fetch latest version..."
            latest_version=$(curl -s https://api.github.com/repos/python-telegram-bot/python-telegram-bot/releases/latest | jq -r '.tag_name')
            if [ -z "$latest_version" ] || [ "$latest_version" == "null" ]; then
              echo "No version found. Retrying in 10 seconds..."
              latest_version=""
              sleep 10
            fi
            attempt=$((attempt + 1))
          done

          if [ -z "$latest_version" ]; then
            echo "Failed to fetch latest version after $max_retries attempts."
            echo "SKIP_PYTHON_UPDATE=true" >> $GITHUB_ENV
            exit 0
          fi

          echo "Latest python-telegram-bot version is $latest_version"
          echo "LATEST_PYTHON_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Read current versi_python from versi file
        if: env.SKIP_PYTHON_UPDATE != 'true'
        id: read_versi
        run: |
          current_version=$(grep -oP '^versi_python=\K.*' versi)
          echo "Current versi_python is $current_version"
          echo "CURRENT_PYTHON_VERSION=$current_version" >> $GITHUB_ENV

      - name: Check if python-telegram-bot version needs updating
        if: env.SKIP_PYTHON_UPDATE != 'true'
        run: |
          if [ "$LATEST_PYTHON_VERSION" != "$CURRENT_PYTHON_VERSION" ]; then
            echo "UPDATE_PYTHON_NEEDED=true" >> $GITHUB_ENV
          else
            echo "UPDATE_PYTHON_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Update versi file for python-telegram-bot
        if: env.UPDATE_PYTHON_NEEDED == 'true' && env.SKIP_PYTHON_UPDATE != 'true'
        run: |
          sed -i "s/^versi_python=.*/versi_python=${LATEST_PYTHON_VERSION}/" versi

      - name: Commit changes for python-telegram-bot
        if: env.UPDATE_PYTHON_NEEDED == 'true' && env.SKIP_PYTHON_UPDATE != 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add versi
          git commit -m "Update versi_python to ${LATEST_PYTHON_VERSION}"
          git push

      - name: Notify Telegram for python-telegram-bot update
        if: env.UPDATE_PYTHON_NEEDED == 'true' && env.SKIP_PYTHON_UPDATE != 'true'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          -d text="Updated versi_python to ${LATEST_PYTHON_VERSION}" \
          -d message_thread_id="${{ secrets.THREAD_UPDATE_ID }}"

      - name: Get latest OpenClash version
        id: get_openclash_version
        run: |
          max_retries=5
          attempt=1
          latest_ver=""
          while [ -z "$latest_ver" ] && [ $attempt -le $max_retries ]; do
            echo "Attempt $attempt to fetch OpenClash version..."
            latest_ver=$(curl -s https://raw.githubusercontent.com/vernesong/OpenClash/package/dev/version | head -n1 | sed "s/^v//g")
            if [ -z "$latest_ver" ]; then
              echo "No version found. Retrying in 10 seconds..."
              sleep 10
            fi
            attempt=$((attempt + 1))
          done

          if [ -z "$latest_ver" ]; then
            echo "Failed to fetch OpenClash version after $max_retries attempts."
            exit 1
          fi

          echo "LATEST_OPENCLASH_VERSION=$latest_ver" >> $GITHUB_ENV

      - name: Read current versi_openclash from versi file
        id: read_openclash
        run: |
          current_openclash_version=$(grep -oP '^versi_openclash=\K.*' versi)
          echo "Current versi_openclash is $current_openclash_version"
          echo "CURRENT_OPENCLASH_VERSION=$current_openclash_version" >> $GITHUB_ENV

      - name: Check if OpenClash version needs updating
        run: |
          if [ "$LATEST_OPENCLASH_VERSION" != "$CURRENT_OPENCLASH_VERSION" ]; then
            echo "UPDATE_OPENCLASH_NEEDED=true" >> $GITHUB_ENV
          else
            echo "UPDATE_OPENCLASH_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Update versi file for OpenClash
        if: env.UPDATE_OPENCLASH_NEEDED == 'true'
        run: |
          sed -i "s/^versi_openclash=.*/versi_openclash=${LATEST_OPENCLASH_VERSION}/" versi

      - name: Commit changes for OpenClash
        if: env.UPDATE_OPENCLASH_NEEDED == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add versi
          git commit -m "Update versi_openclash to ${LATEST_OPENCLASH_VERSION}"
          git push

      - name: Notify Telegram for OpenClash update
        if: env.UPDATE_OPENCLASH_NEEDED == 'true'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          -d text="Updated versi_openclash to ${LATEST_OPENCLASH_VERSION}" \
          -d message_thread_id="${{ secrets.THREAD_UPDATE_ID }}"
          
