name: Update versi_python and Update OpenClash

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get latest release version of python-telegram-bot
        id: get_release
        run: |
          latest_version=$(curl -s https://api.github.com/repos/python-telegram-bot/python-telegram-bot/releases/latest | jq -r '.tag_name')
          echo "Latest python-telegram-bot version is $latest_version"
          # Save the version to an environment file
          echo "LATEST_PYTHON_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Read current versi_python from versi file
        id: read_versi
        run: |
          # Extract the current versi_python value from the versi file
          current_version=$(grep -oP '^versi_python=\K.*' versi)
          echo "Current versi_python is $current_version"
          echo "CURRENT_PYTHON_VERSION=$current_version" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "LATEST_PYTHON_VERSION=${{ env.LATEST_PYTHON_VERSION }}"
          echo "CURRENT_PYTHON_VERSION=${{ env.CURRENT_PYTHON_VERSION }}"

      - name: Check if python-telegram-bot version needs updating
        run: |
          echo "Comparing python-telegram-bot versions..."
          if [ "$LATEST_PYTHON_VERSION" != "$CURRENT_PYTHON_VERSION" ]; then
            echo "Versions are different. Update needed."
            echo "UPDATE_PYTHON_NEEDED=true" >> $GITHUB_ENV
          else
            echo "Versions are the same. No update needed."
            echo "UPDATE_PYTHON_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Update versi file for python-telegram-bot if necessary
        if: env.UPDATE_PYTHON_NEEDED == 'true'
        run: |
          # Replace the versi_python line with the latest version
          sed -i "s/^versi_python=.*/versi_python=${LATEST_PYTHON_VERSION}/" versi

      - name: Commit changes if python-telegram-bot version updated
        if: env.UPDATE_PYTHON_NEEDED == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add versi
          git commit -m "Update versi_python to ${LATEST_PYTHON_VERSION}"
          git push

      - name: Send Telegram notification if python-telegram-bot update found
        if: env.UPDATE_PYTHON_NEEDED == 'true'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          -d text="Updated versi_python to ${LATEST_PYTHON_VERSION}" \
          -d message_thread_id="${{ secrets.THREAD_UPDATE_ID }}"

      - name: Get latest OpenClash version
        id: get_openclash_version
        run: |
          latest_ver=$(curl -s https://raw.githubusercontent.com/vernesong/OpenClash/package/dev/version | head -n1 | sed "s/^v//g")
          echo "Latest OpenClash version is $latest_ver"
          echo "LATEST_OPENCLASH_VERSION=$latest_ver" >> $GITHUB_ENV

      - name: Read current versi_openclash from versi file
        id: read_openclash
        run: |
          # Extract the current versi_openclash value from the versi file
          current_openclash_version=$(grep -oP '^versi_openclash=\K.*' versi)
          echo "Current versi_openclash is $current_openclash_version"
          echo "CURRENT_OPENCLASH_VERSION=$current_openclash_version" >> $GITHUB_ENV

      - name: Check if OpenClash version needs updating
        run: |
          echo "Comparing OpenClash versions..."
          if [ "$LATEST_OPENCLASH_VERSION" != "$CURRENT_OPENCLASH_VERSION" ]; then
            echo "Versions are different. Update needed."
            echo "UPDATE_OPENCLASH_NEEDED=true" >> $GITHUB_ENV
          else
            echo "Versions are the same. No update needed."
            echo "UPDATE_OPENCLASH_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Update versi file for OpenClash if necessary
        if: env.UPDATE_OPENCLASH_NEEDED == 'true'
        run: |
          # Replace the versi_openclash line with the latest version
          sed -i "s/^versi_openclash=.*/versi_openclash=${LATEST_OPENCLASH_VERSION}/" versi

      - name: Commit changes if OpenClash version updated
        if: env.UPDATE_OPENCLASH_NEEDED == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add versi
          git commit -m "Update versi_openclash to ${LATEST_OPENCLASH_VERSION}"
          git push

      - name: Send Telegram notification if OpenClash update found
        if: env.UPDATE_OPENCLASH_NEEDED == 'true'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          -d text="Updated versi_openclash to ${LATEST_OPENCLASH_VERSION}" \
          -d message_thread_id="${{ secrets.THREAD_UPDATE_ID }}"
