name: Delete old workflow runs
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: "0 * * * *"  # This will run every hour. Adjust the schedule as needed.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
