name: Update versi_python and Update python-telegram-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get latest release version of python-telegram-bot
        id: get_release
        run: |
          latest_version=$(curl -s https://api.github.com/repos/python-telegram-bot/python-telegram-bot/releases/latest | jq -r '.tag_name')
          echo "Latest version is $latest_version"
          # Save the version to an environment file
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Read current versi_python from versi file
        id: read_versi
        run: |
          # Extract the current versi_python value from the versi file
          current_version=$(grep -oP '^versi_python=\K.*' versi)
          echo "Current versi_python is $current_version"
          echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "LATEST_VERSION=${{ env.LATEST_VERSION }}"
          echo "CURRENT_VERSION=${{ env.CURRENT_VERSION }}"

      - name: Check if version needs updating
        run: |
          echo "Comparing versions..."
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Versions are different. Update needed."
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          else
            echo "Versions are the same. No update needed."
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Update versi file if necessary
        if: env.UPDATE_NEEDED == 'true'
        run: |
          # Replace the versi_python line with the latest version
          sed -i "s/^versi_python=.*/versi_python=${LATEST_VERSION}/" versi

      - name: Commit changes if version updated
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add versi
          git commit -m "Update versi_python to ${LATEST_VERSION}"
          git push

      - name: Set up Python
        if: env.UPDATE_NEEDED == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the desired Python version

      - name: Force remove files from the 'root/pytelegrambotapi' directory
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git rm -rf files/root/pytelegrambotapi/* || true  # Forcefully remove files in the directory if they exist
          git commit -m "Remove old files from files/root/pytelegrambotapi directory"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pip dependencies and save to root/pytelegrambotapi
        if: env.UPDATE_NEEDED == 'true'
        run: |
          python -m pip install --upgrade pip
          mkdir -p files/root/pytelegrambotapi  # Ensure the directory exists
          pip download python-telegram-bot -d files/root/pytelegrambotapi/

      - name: Zip the pytelegrambotapi directory
        if: env.UPDATE_NEEDED == 'true'
        run: |
          python -c "import shutil; shutil.make_archive('files/root/pytelegrambotapi', 'zip', 'files/root/pytelegrambotapi')"

      - name: Commit and push new downloaded files and zip archive
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add files/root/pytelegrambotapi/ files/root/pytelegrambotapi.zip
          git commit -m "Download and zip python-telegram-bot to files/root/pytelegrambotapi/"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
