name: Update versi File with Latest Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get latest release version
        id: get_release
        run: |
          latest_version=$(curl -s https://api.github.com/repos/python-telegram-bot/python-telegram-bot/releases/latest | jq -r '.tag_name')
          echo "Latest version is $latest_version"
          echo "::set-output name=version::$latest_version"

      - name: Update versi file
        run: |
          # Update the versi file with the new version
          sed -i "s/^versi_python=.*/versi_python=${{ steps.get_release.outputs.version }}/" files/root/pytelegrambotapi/versi
          
          # Check if file has changed
          if [[ $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add files/root/pytelegrambotapi/versi
            git commit -m "Update versi file to version ${{ steps.get_release.outputs.version }}"
            git push
          else
            echo "No changes detected in the versi file."

      - name: Echo the latest version
        run: echo "The latest version is ${{ steps.get_release.outputs.version }}"
