name: Update versi_python

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get latest release version of python-telegram-bot
        id: get_release
        run: |
          latest_version=$(curl -s https://api.github.com/repos/python-telegram-bot/python-telegram-bot/releases/latest | jq -r '.tag_name')
          echo "Latest version is $latest_version"
          # Save the version to an environment file
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Read current versi_python from versi file
        id: read_versi
        run: |
          # Extract the current versi_python value from the versi file
          current_version=$(grep -oP '^versi_python=\K.*' versi)
          echo "Current versi_python is $current_version"
          echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV

      - name: Check if version needs updating
        id: version_check
        run: |
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Versions are different. Update needed."
            echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
          else
            echo "Versions are the same. No update needed."
            echo "UPDATE_NEEDED=false" >> $GITHUB_ENV

      - name: Update versi file if necessary
        if: env.UPDATE_NEEDED == 'true'
        run: |
          # Replace the versi_python line with the latest version
          sed -i "s/^versi_python=.*/versi_python=${LATEST_VERSION}/" versi

      - name: Commit changes if version updated
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add versi
          git commit -m "Update versi_python to ${LATEST_VERSION}"
          git push
