name: Run After OpenClash Version Update

on:
  workflow_run:
    workflows: ["Check and Update OpenClash Version"]
    types:
      - completed

jobs:
  run_secondary_task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Perform secondary action
      run: |
        echo "Running tasks after OpenClash version update"
        # Add any secondary actions you need to run after the version update
