name: Check and Update Tailscale Version

on:
 # schedule:
#    - cron: "0 * * * *"  # This will run every hour. Adjust the schedule as needed.
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get latest Tailscale version
      run: |
        latest_version=$(wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2)
        echo "Latest Tailscale version: $latest_version"
        echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

    - name: Get current version from repo
      run: |
        current_version=$(cat version_tailscale)
        echo "Current version in repo: $current_version"
        echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV

    - name: Check if update is needed
      id: version_check
      run: |
        if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
          echo "::set-output name=update_needed::true"
        else
          echo "::set-output name=update_needed::false"
        fi

    - name: Update version in repo
      if: steps.version_check.outputs.update_needed == 'true'
      run: |
        echo "$LATEST_VERSION" > version_tailscale
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add version_tailscale
        git commit -m "Update Tailscale version to $LATEST_VERSION"
        git push
