name: Download and Upload Specific Tailscale Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight (adjust as needed)

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest Tailscale version
        id: get_version
        run: |
          latest_version=$(wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2)
          echo "Latest version: $latest_version"
          echo "version=$latest_version" >> $GITHUB_ENV

      - name: Download Tailscale tgz
        run: |
          wget https://pkgs.tailscale.com/stable/tailscale_${{ env.version }}_amd64.tgz -O tailscale.tgz

      - name: Extract Tailscale tgz
        run: |
          mkdir tailscale_extract
          tar -xzf tailscale.tgz -C tailscale_extract

      - name: List extracted files for debugging
        run: |
          echo "Listing extracted files:"
          ls -R tailscale_extract

      - name: Move specific binaries to the root directory
        run: |
          mv tailscale_extract/tailscale_${{ env.version }}_amd64/tailscale .
          mv tailscale_extract/tailscale_${{ env.version }}_amd64/tailscaled .

      - name: List moved files for debugging
        run: |
          echo "Listing files in root directory:"
          ls -la

      - name: Add and commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure the specific binaries are tracked
          git add tailscale tailscaled

          # Commit the changes
          git commit -m "Add Tailscale binaries for version ${{ env.version }}"

      - name: Push changes
        run: |
          git push
